-- MySQL Script generated by MySQL Workbench
-- Thu Jul 16 11:02:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Modified to use in final project

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` TINYINT(9) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account` ;

CREATE TABLE IF NOT EXISTS `account` (
  `account_id` TINYINT(9) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(55) NOT NULL,
  `type` TINYINT(9) NOT NULL,
  `user` TINYINT(9) NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_account`
    FOREIGN KEY (`user`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accountType` ;

CREATE TABLE IF NOT EXISTS `accountType` (
  `account` TINYINT(9) NOT NULL,
  `description` VARCHAR(100) NULL,
  `user_type` TINYTEXT NULL,
  CONSTRAINT `fk_account_accountType`
    FOREIGN KEY (`account`)
    REFERENCES `account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `billingInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billingInfo` ;

CREATE TABLE IF NOT EXISTS `billingInfo` (
  `user` TINYINT(9) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(25) NOT NULL,
  `state` VARCHAR(9) NOT NULL,
  `zip` INT NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  UNIQUE INDEX `address_UNIQUE` (`address` ASC),
  CONSTRAINT `fk_user_billingInfo`
    FOREIGN KEY (`user`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendee` ;

CREATE TABLE IF NOT EXISTS `attendee` (
  `user` TINYINT(9) NOT NULL,
  `event` INT NOT NULL,
  `dob` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_user_attendee`
    FOREIGN KEY (`user`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event` ;

CREATE TABLE IF NOT EXISTS `event` (
  `event_id` INT NOT NULL,
  `event_name` VARCHAR(99) NOT NULL,
  `attendee` TINYINT(9) NULL,
  `venue` VARCHAR(20) NOT NULL,
  `organizer` VARCHAR(20) NOT NULL,
  `sponsor` VARCHAR(20) NOT NULL,
  `capacity` INT NOT NULL,
  `promotor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `attendee_idx` (`attendee` ASC) VISIBLE,
  CONSTRAINT `fk_attendee_event`
    FOREIGN KEY (`attendee`)
    REFERENCES `attendee` (`user`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venue` ;

CREATE TABLE IF NOT EXISTS `venue` (
  `venue_id` INT NOT NULL,
  `location` VARCHAR(20) NOT NULL,
  `venue_organizer` VARCHAR(15) NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`venue_id`),
  INDEX `event_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_venue`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organizer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organizer` ;

CREATE TABLE IF NOT EXISTS `organizer` (
  `organizer_id` TINYINT(9) NOT NULL,
  `event` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`organizer_id`),
  INDEX `event_idx` (`event` ASC) VISIBLE,
  CONSTRAINT `fk_event_organizer`
    FOREIGN KEY (`event`)
    REFERENCES `event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sponsor` ;

CREATE TABLE IF NOT EXISTS `sponsor` (
  `sponsor_id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `event` INT NULL,
  `budget` INT NOT NULL,
  PRIMARY KEY (`sponsor_id`),
  INDEX `event_idx` (`event` ASC) VISIBLE,
  CONSTRAINT `fk_event_sponsor`
    FOREIGN KEY (`event`)
    REFERENCES `event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymentType` ;

CREATE TABLE IF NOT EXISTS `paymentType` (
  `payment_type` INT NOT NULL,
  `company_id` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payment_type`),
  INDEX `billing_info_idx` (`address` ASC) VISIBLE,
  CONSTRAINT `fk_billingInfo_paymentType`
    FOREIGN KEY (`address`)
    REFERENCES `billingInfo` (`address`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankAccount` ;

CREATE TABLE IF NOT EXISTS `bankAccount` (
  `account_num` INT NOT NULL,
  `paymentType` INT NOT NULL,
  `bank_id` TINYINT(9) NOT NULL,
  `routing_num` INT NOT NULL,
  PRIMARY KEY (`account_num`, `paymentType`),
  INDEX `paymentType_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `fk_paymentType_bankAccount`
    FOREIGN KEY (`paymentType`)
    REFERENCES `paymentType` (`payment_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `creditCard` ;

CREATE TABLE IF NOT EXISTS `creditCard` (
  `card_type` INT NOT NULL,
  `card_num` DOUBLE NOT NULL,
  `bank_id` TINYINT(9) NOT NULL,
  `cvv` INT NOT NULL,
  `exp_date` VARCHAR(15) NOT NULL,
  `paymentType` INT NOT NULL,
  PRIMARY KEY (`card_type`, `paymentType`),
  INDEX `payment_type_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `fk_paymentType_creditCard`
    FOREIGN KEY (`paymentType`)
    REFERENCES `paymentType` (`payment_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendeeFeedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendeeFeedback` ;

CREATE TABLE IF NOT EXISTS `attendeeFeedback` (
  `user` TINYINT(9) NOT NULL,
  `review_date` VARCHAR(45) NOT NULL,
  `event_id` INT NOT NULL,
  `review` VARCHAR(255) NOT NULL,
  INDEX `attendee_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_attendee_attendeeFeedback`
    FOREIGN KEY (`user`)
    REFERENCES `attendee` (`user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attendeeTicket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendeeTicket` ;

CREATE TABLE IF NOT EXISTS `attendeeTicket` (
  `event_id` INT NOT NULL,
  `expiration` VARCHAR(45) NOT NULL,
  `user` TINYINT(9) NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_user_attendeeTicket`
    FOREIGN KEY (`user`)
    REFERENCES `attendee` (`user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promotor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promotor` ;

CREATE TABLE IF NOT EXISTS `promotor` (
  `promotor_id` TINYINT(9) NOT NULL,
  `event` INT NULL,
  `social_media_accounts` VARCHAR(45) NOT NULL,
  `promotor_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`promotor_id`),
  INDEX `event_idx` (`event` ASC) VISIBLE,
  CONSTRAINT `fk_event_promotor`
    FOREIGN KEY (`event`)
    REFERENCES `event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventCategory` ;

CREATE TABLE IF NOT EXISTS `eventCategory` (
  `event_activities` INT NOT NULL,
  `event_type` VARCHAR(45) NOT NULL,
  `category_desc` VARCHAR(255) NULL,
  `event_id` INT NOT NULL,
  INDEX `event_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_eventCategory`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permit` ;

CREATE TABLE IF NOT EXISTS `permit` (
  `event` INT NOT NULL,
  `alcohol_license` VARCHAR(45) NOT NULL,
  `business_license` VARCHAR(45) NOT NULL,
  `seller_permit` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_event_permit`
    FOREIGN KEY (`event`)
    REFERENCES `event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket` ;

CREATE TABLE IF NOT EXISTS `ticket` (
  `attendee` TINYINT(9) NULL,
  `event` INT NOT NULL,
  `date` INT NOT NULL,
  `price` INT NOT NULL,
  INDEX `event_idx` (`event` ASC) VISIBLE,
  CONSTRAINT `fk_event_ticket`
    FOREIGN KEY (`event`)
    REFERENCES `event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venueLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venueLocation` ;

CREATE TABLE IF NOT EXISTS `venueLocation` (
  `venue` INT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(25) NOT NULL,
  `state` VARCHAR(9) NOT NULL,
  `zip` INT NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  CONSTRAINT `fk_venue_venueLocation`
    FOREIGN KEY (`venue`)
    REFERENCES `venue` (`venue_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venueEmployee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venueEmployee` ;

CREATE TABLE IF NOT EXISTS `venueEmployee` (
  `venue` INT NULL,
  `employee_id` INT NOT NULL,
  `station` INT NULL,
  `salary` INT NOT NULL,
  INDEX `venue_idx` (`venue` ASC) VISIBLE,
  CONSTRAINT `fk_venue_venueEmployee`
    FOREIGN KEY (`venue`)
    REFERENCES `venue` (`venue_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venueActivities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venueActivities` ;

CREATE TABLE IF NOT EXISTS `venueActivities` (
  `venue` INT NULL,
  `activity_type` TINYINT(9) NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  INDEX `venu_idx` (`venue` ASC) VISIBLE,
  CONSTRAINT `fk_venue_venueActivities`
    FOREIGN KEY (`venue`)
    REFERENCES `venue` (`venue_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;

CREATE TABLE IF NOT EXISTS `employee` (
  `employee_id` INT NOT NULL,
  `event` INT NULL,
  `name` VARCHAR(20) NOT NULL,
  `dob` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `event_idx` (`event` ASC) VISIBLE,
  CONSTRAINT `fk_event_employee`
    FOREIGN KEY (`event`)
    REFERENCES `event` (`event_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employeeType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employeeType` ;

CREATE TABLE IF NOT EXISTS `employeeType` (
  `employee_type` INT NOT NULL,
  `employee` INT NULL,
  `shift` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  INDEX `employee_idx` (`employee` ASC) VISIBLE,
  CONSTRAINT `fk_employee_employeeType`
    FOREIGN KEY (`employee`)
    REFERENCES `employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendor` ;

CREATE TABLE IF NOT EXISTS `vendor` (
  `vendor_id` TINYINT(9) NOT NULL,
  `employee_id` INT NOT NULL,
  `station` INT NOT NULL,
  `vendor_type` TINYINT(9) NOT NULL,
  PRIMARY KEY (`vendor_id`),
  INDEX `employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_vendor`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productionTeam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productionTeam` ;

CREATE TABLE IF NOT EXISTS `productionTeam` (
  `team_id` TINYINT(9) NOT NULL,
  `employee_id` INT NOT NULL,
  `station` INT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_productionTeam`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanitationTeam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanitationTeam` ;

CREATE TABLE IF NOT EXISTS `sanitationTeam` (
  `company_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `station` VARCHAR(20) NULL,
  PRIMARY KEY (`company_id`),
  INDEX `employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_sanitationTeam`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;